import { Product } from '@/types';

export const fallbackBakeryProfile = {
  id: 'default',
  bakeryName: 'Blush & Rose Bakery',
  tagline: 'Artisan cakes, handcrafted pastries & bespoke confections',
  description: 'Handcrafted with French butter, Belgian chocolate, and local organic flour. Creating timeless centerpiece cakes for your most cherished celebrations.',
  address: '142 Rosewood Lane, Suite 4, Old Town',
  phone: '+1 (555) 234-5678',
  email: 'orders@blushandrosebakery.com',
  openingHours: 'Tuesday - Saturday: 8:00 AM - 6:30 PM | Sunday: 9:00 AM - 3:00 PM | Monday: Closed',
  pickupInstructions: 'Please ring the doorbell at the side entrance. Have your order number and photo ID ready. Custom cakes are packed in reinforced transport boxes.',
  noticeBanner: '🌸 Welcome! Custom celebration cakes require a minimum 2 days advance notice.',
  minAdvanceNoticeDays: 2,
  depositPercentage: 40,
  cancellationPolicy: 'Cancellations made 72 hours prior to pickup are eligible for a full deposit refund. Later cancellations are non-refundable due to perishable specialty ingredients.',
  defaultSlotCapacity: 4,
  holidayDates: '[]',
  heroImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=1200&auto=format&fit=crop',
};

export const fallbackProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Rosewater Raspberry Chiffon Cake',
    slug: 'rosewater-raspberry-chiffon-cake',
    category: 'Celebration Cakes',
    shortDescription: 'Delicate rosewater sponge layered with tart organic raspberry compote and silky Swiss buttercream.',
    description: 'Our signature centerpiece creation. Layers of cloud-like chiffon sponge delicately infused with Persian organic rosewater, filled with tart homemade raspberry compote and wrapped in silky Swiss meringue buttercream. Adorned with candied rose petals and dried botanicals.',
    price: 58,
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=900&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?q=80&w=900&auto=format&fit=crop',
    ],
    isAvailable: true,
    isFeatured: true,
    preparationTime: '24 Hours',
    isEggless: false,
    ingredients: 'Organic pastry flour, cultured butter, cage-free eggs, organic raspberries, rosewater, cane sugar, vanilla bean.',
    allergens: 'Contains Dairy, Gluten, Eggs. Prepared in a facility handling tree nuts.',
    variants: [
      { id: 'var-1-1', name: '6" Petite (6-8 servings)', price: 58, isAvailable: true },
      { id: 'var-1-2', name: '8" Classic (12-16 servings)', price: 78, isAvailable: true },
      { id: 'var-1-3', name: '10" Grand (20-25 servings)', price: 108, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Vintage Lambeth Vanilla Bean Cake',
    slug: 'vintage-lambeth-vanilla-bean-cake',
    category: 'Celebration Cakes',
    shortDescription: 'Intricate Victorian piped borders with Madagascan bourbon vanilla sponge and salted caramel.',
    description: 'A romantic, timeless Victorian design featuring intricate multi-layered Lambeth scrollwork, delicate scalloped ruffles, and maraschino pearls. Beneath the ornate piping lies velvety Madagascar bourbon vanilla sponge brushed with vanilla bean syrup and filled with salted caramel cream.',
    price: 68,
    imageUrl: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?q=80&w=900&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1562440499-64c9a111f713?q=80&w=900&auto=format&fit=crop',
    ],
    isAvailable: true,
    isFeatured: true,
    preparationTime: '48 Hours',
    isEggless: false,
    ingredients: 'Bourbon vanilla beans, cultured butter, whole milk, unbleached flour, cane sugar, egg whites, sea salt caramel.',
    allergens: 'Contains Gluten, Dairy, Eggs.',
    variants: [
      { id: 'var-2-1', name: '6" Petite (6-8 servings)', price: 68, isAvailable: true },
      { id: 'var-2-2', name: '8" Classic (12-16 servings)', price: 92, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Belgian Dark Chocolate Truffle Cake',
    slug: 'belgian-dark-chocolate-truffle-cake',
    category: 'Celebration Cakes',
    shortDescription: '70% Valrhona dark chocolate sponge filled with whipped espresso ganache and cocoa nib crunch.',
    description: 'Rich, fudgy layers made from 70% single-origin Belgian chocolate, soaked in light espresso syrup and sandwiched with whipped dark chocolate ganache. Finished with chocolate curls, edible 24k gold leaf, and sea salt flakes.',
    price: 62,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=900&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=900&auto=format&fit=crop',
    ],
    isAvailable: true,
    isFeatured: true,
    preparationTime: '24 Hours',
    isEggless: false,
    ingredients: '70% dark Belgian cocoa, Dutch butter, organic milk, espresso, eggs, turbinado sugar, gold leaf.',
    allergens: 'Contains Dairy, Gluten, Eggs.',
    variants: [
      { id: 'var-3-1', name: '6" Petite (6-8 servings)', price: 62, isAvailable: true },
      { id: 'var-3-2', name: '8" Classic (12-16 servings)', price: 85, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Matcha White Chocolate Strawberry Opera',
    slug: 'matcha-white-chocolate-strawberry-opera',
    category: 'Celebration Cakes',
    shortDescription: 'Ceremonial Uji matcha sponge layers with white chocolate ganache and strawberry jelly.',
    description: 'An elegant interpretation of the French opera cake. Six ultra-thin layers of Japanese ceremonial matcha joconde almond sponge, house-made strawberry reduction gelée, and velvety Ivoire 35% white chocolate ganache.',
    price: 65,
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?q=80&w=900&auto=format&fit=crop',
    galleryUrls: [
      'https://images.unsplash.com/photo-1535141192574-5d4897c13136?q=80&w=900&auto=format&fit=crop',
    ],
    isAvailable: true,
    isFeatured: false,
    preparationTime: '24 Hours',
    isEggless: false,
    ingredients: 'Almond flour, Japanese Uji matcha, white chocolate, organic strawberries, butter, eggs.',
    allergens: 'Contains Tree Nuts (Almonds), Dairy, Gluten, Eggs.',
    variants: [
      { id: 'var-4-1', name: 'Standard 7" Square', price: 65, isAvailable: true },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
